-- =====================================================================
-- db/schema.sql — practitioner survey database (Supabase project ssvc-survey)
--
-- Governs: A38.6 (scales, rater questions), A39.5 (platform, order rules).
-- To be recorded at A40 before launch, with the deployed commit:
--   * SURVEY_VERSION = 'v1'
--   * years bands: lt_2, 2_4, 5_9, 10_plus (lt_2 = the A38.6 screen)
--   * repeat spacing read strictly: at least 8 OTHER items between the two
--     showings of a repeated scenario (second position - first >= 9)
--   * keepalive table: free-plan pause mitigation, holds no survey data
--
-- The public (anon) role may INSERT only, and only into named columns:
-- it cannot read, update or delete anything, and cannot set timestamps.
-- Stored values are codes; the page shows display labels (A39.4).
-- This project never connects to the research database (A39.5).
--
-- Run once, on an empty project. Tested first with db/test_schema.sql.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Keep-alive (created on the live project 27 Sep 2026; recorded here)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.keepalive (
    id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pinged_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.keepalive ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.keepalive FROM anon, authenticated, PUBLIC;

-- ---------------------------------------------------------------------
-- Item order rule (A38.4, A38.6, A39.5)
-- 23 items: scenarios 1-20 once each, plus scenarios 2, 6 and 12 twice.
-- The second showing of each repeat comes at least 9 positions after
-- the first, i.e. with at least 8 other items between them.
-- ---------------------------------------------------------------------
CREATE FUNCTION public.survey_item_order_ok(o smallint[])
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $$
  SELECT
        o IS NOT NULL
    AND array_ndims(o) = 1
    AND cardinality(o) = 23
    AND array_position(o, NULL) IS NULL
    AND (SELECT bool_and(v BETWEEN 1 AND 20) FROM unnest(o) AS u(v))
    AND (SELECT bool_and(cardinality(array_positions(o, s::smallint))
                         = CASE WHEN s IN (2, 6, 12) THEN 2 ELSE 1 END)
           FROM generate_series(1, 20) AS g(s))
    AND (SELECT bool_and((array_positions(o, s::smallint))[2]
                       - (array_positions(o, s::smallint))[1] >= 9)
           FROM unnest(ARRAY[2, 6, 12]) AS r(s))
$$;

-- ---------------------------------------------------------------------
-- Sessions: one per rater, created when the rater starts.
-- session_id is generated by the page (crypto.randomUUID), because the
-- public role cannot read back a database-generated key.
-- ---------------------------------------------------------------------
CREATE TABLE public.sessions (
    session_id     uuid        PRIMARY KEY,
    survey_version text        NOT NULL CHECK (survey_version = 'v1'),
    item_order     smallint[]  NOT NULL CHECK (public.survey_item_order_ok(item_order)),
    consent_given  boolean     NOT NULL CHECK (consent_given),
    started_at     timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- About the rater (A38.6). No name, no email, nothing identifying.
-- ---------------------------------------------------------------------
CREATE TABLE public.screening (
    session_id       uuid        PRIMARY KEY REFERENCES public.sessions (session_id),
    years_band       text        NOT NULL CHECK (years_band IN ('lt_2', '2_4', '5_9', '10_plus')),
    role_band        text        NOT NULL CHECK (role_band IN ('analyst', 'engineer', 'lead', 'manager')),
    works_at_mssp    boolean     NOT NULL,
    used_ssvc_before boolean     NOT NULL,
    submitted_at     timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Ratings: one row per item shown (A38.6). All four ratings required.
-- ---------------------------------------------------------------------
CREATE TABLE public.responses (
    session_id      uuid        NOT NULL REFERENCES public.sessions (session_id),
    position        smallint    NOT NULL CHECK (position BETWEEN 1 AND 23),
    scenario        smallint    NOT NULL CHECK (scenario BETWEEN 1 AND 20),
    showing         smallint    NOT NULL CHECK (showing IN (1, 2)),
    system_exposure text        NOT NULL CHECK (system_exposure IN ('small', 'controlled', 'open')),
    human_impact    text        NOT NULL CHECK (human_impact IN ('low', 'medium', 'high', 'very_high')),
    action          text        NOT NULL CHECK (action IN ('defer', 'scheduled', 'out_of_cycle', 'immediate')),
    confidence      smallint    NOT NULL CHECK (confidence BETWEEN 1 AND 5),
    answered_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, scenario, showing),
    UNIQUE (session_id, position),
    CHECK (showing = 1 OR scenario IN (2, 6, 12))
);

-- A rating must match the rater's stored order: the scenario at that
-- position, and the right showing (first or second). Runs with the
-- owner's rights because the public role cannot read sessions.
CREATE FUNCTION public.responses_match_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
    o smallint[];
    expected_showing smallint;
BEGIN
    SELECT s.item_order INTO o
      FROM public.sessions AS s
     WHERE s.session_id = NEW.session_id;

    IF o IS NULL OR o[NEW.position] IS DISTINCT FROM NEW.scenario THEN
        RAISE EXCEPTION 'rating does not match the stored item order'
              USING ERRCODE = '23514';
    END IF;

    SELECT count(*) INTO expected_showing
      FROM generate_subscripts(o, 1) AS i
     WHERE i <= NEW.position AND o[i] = NEW.scenario;

    IF expected_showing IS DISTINCT FROM NEW.showing THEN
        RAISE EXCEPTION 'showing does not match the stored item order'
              USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.responses_match_order() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER responses_match_order
BEFORE INSERT ON public.responses
FOR EACH ROW EXECUTE FUNCTION public.responses_match_order();

-- ---------------------------------------------------------------------
-- Access: insert-only for the public role, named columns only.
-- Supabase grants new public tables to anon and authenticated by
-- default; everything is revoked first, then INSERT granted back.
-- ---------------------------------------------------------------------
REVOKE ALL ON public.sessions, public.screening, public.responses
    FROM anon, authenticated, PUBLIC;

GRANT INSERT (session_id, survey_version, item_order, consent_given)
    ON public.sessions TO anon;
GRANT INSERT (session_id, years_band, role_band, works_at_mssp, used_ssvc_before)
    ON public.screening TO anon;
GRANT INSERT (session_id, position, scenario, showing,
              system_exposure, human_impact, action, confidence)
    ON public.responses TO anon;

ALTER TABLE public.sessions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screening ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_insert ON public.sessions  FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_insert ON public.screening FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY anon_insert ON public.responses FOR INSERT TO anon WITH CHECK (true);
-- No SELECT, UPDATE or DELETE policy exists for any role but the owner.

COMMIT;
